### ISSUE TITLE
Schets wat we gaan doen

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Backend#10]
@WatchFriends/frontend-webdevelopers: Korte schets, brainstorm over wat onze frontend zal doen en hoe de sockets zullen werken.  

**Ter herinnering:** er moet realtime communicatie zijn via sockets.

Ik stel dus voor indien je een serie gevonden hebt, kunt bekijken wie dit al bekeken heeft + dat alles realtime update.

**PS:** Betere naam voor deze repo zal welkom zijn.

**Comment by HeinPauwelyn** [comment]
**@WatchFriends/android-developers & @WatchFriends/backend-webdevelopers:** zou ook tof zijn indien de frontend website zal kunnen communiceren met debackend

**Comment by ExCellRaD** [comment]
> er moet realtime communicatie zijn via sockets.
> Ik stel dus voor indien je een serie gevonden hebt, kunt bekijken wie dit al bekeken heeft + dat alles realtime update.

Dit kan via beoordelingen gebeuren (was ook opmerking op leho), hoe is wat jij voorstelt realtime?

> zou ook tof zijn indien de android applicatie zal kunnen communiceren met frontend.

Op welke manier precies? Waarom is dit nodig?

**Comment by HeinPauwelyn** [comment]
> hoe is wat jij voorstelt realtime?

Vanaf er iets gebeurt, direct alle andere clients geïnformeerd wordt. bv zoals chat of meldingen op GitHub als er een nieuwe comment toegevoegd wordt.

> Op welke manier precies? Waarom is dit nodig?

Stel: ik beoordeel een serie of markeer hem als gezien via de app,wordt dit direct doorgestuurd naar de frontend zoals hierboven beschreven.
